from random import Random, SystemRandom
import string
import re
class NonListEsqueError(ValueError):
    pass
class NonHashError(ValueError):
    pass
qweeeewwwkjkakhdbskjhsdbfkjhsdbjkhhfbsdfhdafkhhhhhhfad=SystemRandom().choice
class random_plus(Random):
    def randint(self,min,max,step=1):
        if min>max:
            min,max=max,min
        elif min==max:
            return min
        return self.randrange(min,max+1,step)
    characters=list(string.digits+string.ascii_letters)
    keysmashers=list(string.printable)
    def shuffle(self, og):
        if isinstance(og, list):
            og[:]=self.sample(list(og),len(og))
            return og
        elif not isinstance(og, (set, tuple)):
            raise NonListEsqueError('that isn\'t a list-ish datatype!')
        else:
            return self.sample(list(og),len(og))
    def keys(self,original,count=1):
        if isinstance(original,dict):
            og_list=list(original.keys())
        else:
            raise NonHashError('That\'s not a dict.')
        return [self.choice(og_list) for _ in range(count)]
    def values(self,original,count=1):
        if isinstance(original,dict):
            og_list=list(original.values())
        else:
            raise NonHashError('That\'s not a dict')
        return [self.choice(og_list) for _ in range(count)]
    def alphanumerical(self,length):
        return ''.join(qweeeewwwkjkakhdbskjhsdbfkjhsdbjkhhfbsdfhdafkhhhhhhfad(self.characters) for qwertyuiopasdfghjklzxcvbnm in range(length-1))+"q"
    def truth(self, True_weight=50, Total_weight=100):
        if True_weight>Total_weight:
            True_weight,Total_weight=Total_weight,True_weight
        return self.choices([True,False], weights=[True_weight, Total_weight-True_weight])[0]
    def keysmash(self,len_mod):
        qwertqwertqertqwertqertqrtqwertqwertqwertqwert=''.join(self.choice(string.printable) for qwertyuiopqwertyuiopqwertyuioplkjhgfdsalkjhgfdsalkjhgfdsazxcvbnmzxcvbnmzxcvbnm in range(300+abs(len_mod)))
        print(qwertqwertqertqwertqertqrtqwertqwertqwertqwert)
        return qwertqwertqertqwertqertqrtqwertqwertqwertqwert
        things = ["You step on a crunchy leaf. Satisfaction achieved. +2 health",
        "A bird chirps at you like it knows something. -2 health",
        "You find a shiny pebble. +4 health",
        "You drop your snack but it lands on the wrapper. +2 health",
        "You sneeze unexpectedly and scare yourself. -2 health",
        "A friendly dog approaches you for pets. +6 health",
        "You walk into a low-hanging branch. -4 health",
        "You discover a vending machine that actually works. +4 health",
        "You misjudge a step and do the awkward stumble. -2 health",
        "You see a rainbow. +6 health",
        "You accidentally sit on your own hand. -2 health",
        "You find a coupon for something you actually buy. +4 health",
        "You hear someone say your name but nobody is there. -2 health",
        "You get a perfect Wi-Fi signal. +6 health",
        "You forget what you were saying mid-sentence. -2 health",
        "You pet a very fluffy cat. +8 health",
        "You step in a puddle while wearing socks. -6 health",
        "You find a dollar on the ground. +2 health",
        "You get startled by your own reflection. -2 health",
        "You see a cloud shaped like a dinosaur. +4 health",
        "You accidentally bite your cheek. -4 health",
        "You smell cookies baking somewhere. +2 health",
        "You get a high-five from a friend. +4 health",
        "You drop your phone but it survives. +6 health",
        "You walk through a spider web. -4 health",
        "You remember a wholesome childhood memory. +6 health",
        "You stub your toe on the corner of a table. -6 health",
        "You hear your favorite song unexpectedly. +4 health",
        "You find a comfy chair. +2 health",
        "You trip but recover like a ninja. +2 health",
        "You slip on a banana peel. -4 health",
        "You see a flying gorilla. +2 health",
        "You're invited to a birthday party and eat too much junk. -10 health",
        "A wizard casts 'Minor Inconvenience.' -2 health",
        "The life tax arrives. -2 health",
        "You accidentally step on a LEGO. -40 health",
        "A friendly squirrel hands you an acorn of encouragement. +2 health",
        "You trip over your own shoelaces in public. -2 health",
        "You find a perfectly round rock. +2 health",
        "A sudden gust of wind steals your hat. -2 health",
        "You laugh at a funny memory. +4 health",
        "A raccoon judges your life choices from a trash can. -2 health",
        "You drink water and feel surprisingly refreshed. +2 health",
        "You stub your toe on absolutely nothing. -2 health",
        "A butterfly lands on you. +6 health",
        "You misread a text message and panic for no reason. -2 health",
        "You find $1 on the ground. +2 health",
        "You drop your snack on the floor. -2 health",
        "A dog wags its tail at you. +6 health",
        "You forget why you walked into the room. -2 health",
        "You successfully parallel park on the first try. +4 health",
        "You sneeze five times in a row. -2 health",
        "You sit down on a chair that is slightly colder than expected. -2 health",
        "You get a high-five from a stranger. +4 health",
        "You accidentally bite your tongue. -4 health",
        "You see a double rainbow. +8 health",
        "You wake up before your alarm and feel betrayed. -2 health",
        "You find a perfectly ripe piece of fruit. +4 health",
        "You drop your phone but it doesn’t crack. +6 health",
        "You walk into a spider web. -4 health",
        "You remember something embarrassing from years ago. -2 health",
        "You smell cookies baking somewhere. +2 health",
        "You forgot your homework at home. -4 health",
        "You aced a surprise quiz. +6 health",
        "You tripped going up the stairs in front of everyone. -2 health",
        "You found a pencil on the ground that writes perfectly. +4 health",
        "You accidentally sat in someone else's assigned seat. -2 health",
        "You got partnered with your best friend for a project. +6 health",
        "You spilled water on your notes. -4 health",
        "You got a compliment from a teacher. +4 health",
        "You realized the test is actually next week. +2 health",
        "You realized the test is actually TODAY. -6 health",
        "You forgot your locker combination for a moment. -2 health",
        "You found an open computer in the lab. +4 health",
        "You dropped your binder and papers went everywhere. -4 health",
        "You got extra credit for answering a question. +6 health",
        "You got hit by a rogue dodgeball in gym class. -4 health",
        "You finished your assignment early. +4 health",
        "You accidentally called the teacher 'mom' or 'dad'. -2 health",
        "You found a comfy seat in the library. +2 health",
        "You got caught daydreaming in class. -2 health",
        "You remembered all your supplies for once. +4 health",
        "You absolutely crushed a huge exam you thought you'd fail. +30 health",
        "You opened your backpack and discovered a forgotten project due TODAY. -60 health",
        "You get invited to sit at the cool table for once. +6 health",
        "You accidentally wave at someone who wasn’t waving at you. -2 health",
        "You post something online and it gets way more likes than expected. +4 health",
        "You try to look cool and almost fall over. -2 health",
        "You get complimented on your outfit. +4 health",
        "You get called out in front of the class for something you didn’t do. -4 health",
        "You make a joke and the whole group laughs. +6 health",
        "You make a joke and nobody hears it. -2 health",
        "You walk into class and someone says 'Yooo!' like you're famous. +4 health",
        "You walk into class and immediately trip. -2 health",
        "You get added to a group chat you actually like. +4 health",
        "You get removed from a group chat for no reason. -4 health",
        "You get a shoutout during morning announcements. +6 health",
        "You get caught talking when the room suddenly goes silent. -2 health",
        "You accidentally interrupt someone’s story. -2 health",
        "You start a trend without meaning to. +8 health",
        "You try to start a trend and it flops instantly. -4 health",
        "You get invited to a group hangout. +6 health",
        "You get left on read for 3 hours. -2 health",
        "You get left on read for 3 days. -6 health",
        "You make a new friend unexpectedly. +4 health",
        "You forget someone’s name right after they tell you. -2 health",
        "You get tagged in a good photo. +4 health",
        "You get tagged in a terrible photo. -4 health",
        "You walk into the cafeteria and someone waves excitedly at you. +4 health",
        "You walk into the cafeteria and realize they were waving at someone behind you. -2 health",
        "You see some mean comments about you online. It stings, but you shake it off. -12 health",
        "The person you like waves at you from across the hallway. +6 health",
        "The person you like smiles at you unexpectedly. +4 health",
        "The person you like says hi to you by name. +8 health",
        "The person you like compliments your outfit. +6 health",
        "The person you like sits near you in class. +4 health",
        "The person you like laughs at your joke. +6 health",
        "The person you like holds the door open for you. +2 health",
        "The person you like asks you for help on homework. +4 health",
        "The person you like sends you a funny meme. +6 health",
        "The person you like remembers something you said weeks ago. +8 health",
        "You wave at the person you like, but they don’t see you. -2 health",
        "You try to talk to the person you like and stumble over your words. -2 health",
        "You drop something right in front of the person you like. -2 health",
        "You accidentally walk into the person you like while distracted. -4 health",
        "You say something you immediately regret in front of your crush. -2 health",
        "You think the person you like is waving at you, but they were waving at someone behind you. -2 health",
        "You try to look cool in front of your crush and almost fall. -8 health",
        "Your least favorite teacher is out today. Instant relief. +6 health",
        "A substitute walks in… it's Mr. P, the chillest sub ever. +8 health",
        "Mr. P lets the class have a study hall instead of a lecture. +4 health",
        "Mr. P mispronounces your name but tries really hard. +2 health",
        "Mr. P brings in a random fun fact that actually blows your mind. +4 health",
        "Your bad teacher left a huge packet for the sub to assign. -4 health",
        "Mr. P ignores the packet and says 'We’re not doing that today.' +6 health",
        "Mr. P lets you choose your own seat. +2 health",
        "Mr. P accidentally gives the wrong instructions and everyone is confused. -2 health",
        "Your bad teacher left a pop quiz for the sub to give. -6 health",
        "Mr. P shrugs and says 'Nah, we’re skipping this.' +6 health",
        "Mr. P plays a documentary that has nothing to do with the class. +2 health",
        "Your bad teacher returns halfway through class unexpectedly. -4 health",
        "Mr. P gives you extra time to finish your work. +4 health",
        "Mr. P tells a story that goes wildly off-topic but is actually interesting. +4 health",
        "Your bad teacher left a note saying 'No talking.' Mr. P ignores it. +2 health",
        "Mr. P accidentally assigns double the homework. -4 health",
        "Mr. P realizes the homework was too much and cancels it. +4 health",
        "Your bad teacher left a video with 40 questions. -6 health",
        "Mr. P loses the worksheet pile and decides it's optional. +6 health",
        "Mr. P walks in and the whole class cheers. +6 health",
        "Mr. P lets everyone have a chill day because 'you all look tired.' +4 health",
        "Mr. P brings in a giant bag of markers and says 'Go wild.' +2 health",
        "Mr. P accidentally calls the principal 'dude.' +2 health",
        "Mr. P gives you a sticker for no reason. +4 health",
        "Mr. P tells a story that is way more interesting than the actual lesson. +4 health",
        "Mr. P forgets the attendance sheet and just shrugs. +2 health",
        "Mr. P lets you work with your friends. +4 health",
        "Mr. P misreads the instructions and assigns the wrong page. -2 health",
        "Mr. P realizes the assignment is confusing and cancels it. +4 health",
        "Mr. P gives the class a brain break. +2 health",
        "Mr. P accidentally knocks over a stack of textbooks. -2 health",
        "Mr. P brings in a random object and calls it 'today’s learning tool.' +2 health",
        "Mr. P lets you leave class 2 minutes early. +2 health",
        "Mr. P tries to use the smartboard and it glitches instantly. -2 health",
        "The person you like waves at you enthusiastically. +6 health",
        "The person you like asks how your day is going. +4 health",
        "The person you like sits next to you on purpose. +6 health",
        "The person you like laughs at something you said. +4 health",
        "The person you like remembers your favorite snack. +6 health",
        "The person you like walks by and says your name with a smile. +4 health",
        "The person you like holds the door for you. +2 health",
        "The person you like asks if you want to work together. +4 health",
        "The person you like accidentally bumps into you and apologizes with a smile. +2 health",
        "You wave at your crush but they don’t see you. -2 health",
        "You try to talk to your crush and forget what you were saying. -2 health",
        "You drop something right in front of your crush. -2 health",
        "You walk into a desk while trying to look cool. -2 health",
        "You think your crush is waving at you, but they were waving at someone behind you. -2 health",
        "You get picked on by the school bully on the first day of the year. Rough start. -20 health",
        "You accidentally get a pencil stuck in the ceiling on day one. -2 health",
        "You see a floating pair of 衃's and think it's a bad omen. -2 health",
        "You open your locker and a single confetti popper goes off for no reason. +2 health",
        "A random kid sprints past you yelling 'I’m late for EVERYTHING!' and vanishes around a corner. -0 health",
        "You trip over absolutely nothing. Gravity just wanted attention today. -2 health",
        "You find a mysterious hall pass signed by someone named 'The Janitor King.' -0 health",
        "A teacher calls you by the wrong name all day, and you never correct them. -2 health",
        "A pigeon lands on your head, stays there for three seconds, then leaves like it had an appointment. +0 health",
        "You sneeze so loudly that three classrooms over someone yells 'Bless you!' -0 health",
        "You accidentally walk into the wrong classroom and immediately walk back out. Everyone saw. -2 health",
        "Your teacher tries to turn on the projector but only succeeds in dimming the lights. -2 health",
        "Your teacher opens the calculator app instead of the slideshow. -2 health",
        "Your teacher forgets their laptop password again and gives up instantly. -0 health",
        "Your teacher taps the smartboard so hard it freezes in fear. -4 health",
        "Your teacher tries to play a video but opens 47 tabs instead. -2 health",
        "Your teacher blames the computer while it’s clearly unplugged. -4 health",
        "Your teacher prints something and has no idea where it came out. -2 health",
        "Your teacher tries to unmute themselves but shuts down the whole computer. -4 health",
        "Your teacher emails themselves a photo instead of saving it. -0 health",
        "Your teacher tries to zoom in on a paper by pinching it. -2 health",
        "Your teacher says 'This worked yesterday' for the tenth time. -0 health",
        "Your teacher accidentally screenshares their desktop full of cat photos. -2 health",
        "Your teacher tries to copy and paste but prints the document instead. -2 health",
        "Your teacher wonders why the Wi‑Fi is broken while airplane mode is on. -4 health",
        "Your teacher panics because they can’t exit full screen. -2 health",
        "Your teacher plays audio at maximum volume and scares everyone. -4 health",
        "Your teacher says 'I’m not a tech person' as the class nods knowingly. -0 health",
        "Your teacher drags a file and accidentally moves the entire window off-screen. -2 health",
        "Your teacher opens the wrong slideshow for the wrong class. -2 health",
        "Your teacher tries to write on the smartboard with a real marker. -6 health",
        "Your teacher clicks around saying 'Why is it doing that?' -0 health",
        "Your teacher tries to save a file but deletes it instead. -4 health",
        "Your teacher misses the USB port by a full inch. -2 health",
        "Your teacher says 'Technology hates me' for the fifth time today. -0 health",
        "Your teacher rotates their head instead of rotating a PDF. -0 health",
        "Your teacher forgets to switch inputs and blames the projector. -2 health",
        "Your teacher tries to scroll on the smartboard with their sleeve. -2 health",
        "Your teacher loses their mouse on the second monitor. -2 health",
        "Your teacher plays a video in 144p and pretends it’s fine. -0 health",
        "Your teacher accidentally prints 99 copies of the homework. -4 health",
        "Your teacher tries to log in but caps lock is on. -2 health",
        "Your teacher calls a 7‑year‑old laptop 'too new.' -0 health",
        "Your teacher mistypes a URL three times in a row. -2 health",
        "Your teacher opens a new window instead of switching tabs. -0 health",
        "Your teacher tries to take attendance but the program crashes. -2 health",
        "Your teacher’s computer updates right in the middle of class. -4 health",
        "Your teacher resizes a window into microscopic mode. -2 health",
        "Your teacher tries to play audio but the speakers aren’t connected. -2 health",
        "Your teacher loses a file that was literally on the desktop. -0 health",
        "Your teacher tries to highlight text but drags the whole paragraph. -2 health",
        "Your teacher misses the button they’re clicking five times in a row. -0 health",
        "Your teacher says 'Back in my day we didn’t need computers.' -2 health",
        "Your teacher opens twelve copies of the same document. -2 health",
        "Your teacher blasts the class with sudden loud audio. -4 health",
        "Your teacher tilts their head to 'fix' the sideways screen. -0 health",
        "Your teacher clicks repeatedly on a frozen screen, making it worse. -2 health",
        "Your teacher emails the wrong class the wrong file. -2 health",
        "Your teacher tries to close a tab but closes the entire browser. -4 health",
        "Your teacher starts the slideshow on slide 47 for no reason. -2 health",
        "Your teacher tries to block gaming sites but accidentally blocks the homework page instead. -2 health",
        "Your teacher proudly announces they blocked all games, but only the math tools stop working. -2 health",
        "Your teacher tries to restrict distractions and ends up blocking the entire assignment. -4 health",
        "Your teacher updates the filter and suddenly the school website stops loading. -2 health",
        "Your teacher tries to block a game but blocks the grading portal instead. -4 health",
        "Your teacher says the games are gone, but only the research tabs disappear. -2 health",
        "Your teacher tries to disable entertainment sites and accidentally disables the lesson plan. -2 health",
        "Your teacher blocks the wrong category and now educational videos won’t play. -2 health",
        "Your teacher tries to stop students from gaming and ends up blocking the online textbook. -4 health",
        "Your teacher says 'No more games!' right as the entire class loses access to their work. -2 health",
        "Mr. Smith (magically) figures out his projector, shocking the entire class. -2 health",
        "Ms. Ross updates the filter and accidentally blocks everything, including the assignment, the class website, and her own email. -2 health",
        "Mr. O accidentally unplugs the router instead of his charger. -2 health",
        "Ms. Lee tries to turn on the projector but hits the light switch instead. -2 health",
        "Ms. Wardlaw restarts the computer by pressing every key except the power button. -2 health",
        "Mr. Na tries to fix the Wi‑Fi by shaking the laptop. -0 health",
        "Mr. O plugs his charger into the smartboard port and wonders why nothing works. -2 health",
        "Two students argue over whose turn it is to use the class computer, and neither of them wins. -2 health",
        "Someone bumps into you in the hallway and insists it was your fault. -2 health",
        "Two students start loudly debating which answer is correct, even though both are wrong. -2 health",
        "A student cuts the lunch line and pretends not to notice the 20 people behind them. -2 health",
        "Two students fight over the last pencil in the supply bin like it’s legendary loot. -2 health",
        "A group project turns into a group argument within 30 seconds. -4 health",
        "Someone takes your seat and claims 'there are no assigned seats' even though everyone knows there are. -2 health",
        "Two students start arguing across the room during silent work time. -2 health",
        "A student accuses another of stealing their notes, only to find them in their own backpack. -0 health",
        "Someone kicks your chair from behind and pretends it wasn’t them. -2 health",
        "Two students argue about who gets the last Chromebook, and it dies instantly when they turn it on. -2 health",
        "A student loudly insists they turned in the homework, even though they definitely didn’t. -0 health",
        "Someone takes your charger without asking and returns it at 2% battery. -2 health",
        "Two students start a heated debate about which teacher is stricter. -0 health",
        "A student blames you for moving their stuff even though you weren’t in the room. -2 health",
        "Someone borrows your pencil and immediately loses it. -2 health",
        "Two students argue over who gets the 'good' calculator. -2 health",
        "A student accuses another of cheating on a quiz, causing unnecessary drama. -2 health",
        "Someone steps on your shoe in the hallway and doesn’t apologize. -2 health",
        "Two students start arguing about who gets the window seat. -2 health",
        "Gravity suddenly glitches and everything in the room starts falling toward you, but it stops just in time and you end up buried under free snacks instead. +6 health",
        "A student tries to refresh a page and accidentally deletes all their browser cookies, instantly logging themselves out of every account they’ve ever touched. -2 health",
        "A student gets a phone call home because they installed Linux on their personal Chromebook, but the teacher thought it was a school device and panicked. -2 health",
        "A student downloads a suspicious malware .exe file, but it somehow does absolutely nothing except close their tabs. -2 health",
        "A student installs Borealis on their Chromebook even though the project was canceled weeks ago, confusing the teacher, the IT department, and possibly the laws of time. -2 health",
        "A mysterious lunch cart appears out of nowhere and hands you a perfectly cooked feast. +50 health",
        "A glowing cafeteria tray descends from the ceiling offering unlimited mashed potatoes. +40 health",
        "A cosmic chef materializes, compliments your posture, and gives you a legendary sandwich. +60 health",
        "A portal opens and a future version of you hands over premium snacks. +80 health",
        "The vending machine glitches and dispenses everything for free, neatly stacked. +20 health",
        "A turkey wearing sunglasses gives you a thumbs‑up and a full meal. +100 health",
        "... +0 health",
        "Anthony makes a game called 'Random Chaos'. +2 health",
        "Ira makes a game just like 'Random Chaos' with the same name, but on Scratch. +2 health",
        "You hear a knock on your door. You open it, overcome with curiosity, only to see a horse standing on it's hind legs, saying \"No one will ever believe you\" and punches you in the stomach before walking away. -6 health",
        f"{''.join(set(string.printable))}. -2 health.",
        "Ms. Ross triggers the fire alarm instead of unplugging her charger. You are forced to evacuate. -4 health",
        "Brooks being Brooks. -2 health",
        "You're the only kid here in school take you're kid to work day... -4 health",
        "Mabel implodes the world. -200 health",
        "A flying cheeseburger appears. +4 health",
        "You open up a battery and eat the Lithium. -20 health",
        "You eat \033[3mbrocoli\033[3m. -2 health",
        "You get a cold. -10 health",
        "A turkey ealts your food. -20 health",
        "... -10 health",
        "Ooga Booga! -12 health",
        "Nathan helps you with your homework. +2 health",
        "Alex Stringer gives you a snack. +20 health",
        "June becomes less emo. -4 health",
        "Mr. Na gives a free day. +2 health",
        "You find $5 on the ground. +10 health",
        "You watch play video games for 8 hours. +8 health",
        "You play video games for 12 hours. +12 health",
        "Mr. Lee gives you a 1-minute lunch detention for not doing an assignment. -2 health",
        "You breathe CO₂. -2 health ",
        "Your locker is jammed and you are late to 4th period. -200 health",
        "UNGA BUNGA! +4 health",
        "... +46 health",
        "A chicken falls off of a plane's storage and hits you in the in the head. -80 health",
        "We decided that you needed a boost. +6 health",
        "... -20 health",
        "Arpan becomes smarter in Algebra I. +2 health",
        "Josh from Pd. 5 Algebra I just being him. -100 health",
        "Everyone tells Chloe that they like her haircut. -4 health",
        "Dalton gets accidentally in the wrong Algebra I class for Desmos. -4 health",
        "Everyone thinks Khloe is Chloe. -4 health",
        "You're underprepared for a pop quiz... -20 health",
        "Otis and Ephialtes the giants appear and explode stuff. -100 health",
        "Mr. Smith makes a new game, 'Transformers'. +6 health",
        "The parabola is reflected over the x-axis, and the celing collapses over only you're head. -60 health",
        "You lose twenty health. -20 health",
        "You relax under a concave down parabola. +8 health",
        "You finish your homework. +2 health",
        "The cosmos smile upon you. +2 health",
        "You accidentally go to deltamat.com instead of deltamath.com, and your teacher gets mad that your 'buying forklifts'. -4 health",
        "\\/. -2 health",
        "Because we felt like it... -6 health",
        "You eat a banana. +2 health",
        "You play minecraft. +8 health",
        "Patrick beats a level on Drive Mad. +4 health",
        self.keysmash(0)+". -20 health",
        "You find out that Arpan is an alien. -12 health",
        ".[{-_-}]. -6 health", "===================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================. +300 health",
        "Joshua is beng tuff. +10 health",
        "!!!!!!!!!!!!!!!!!!!!!. \u202e+20 health",
        "\u202e+10 health",
        ". +200 health since I'm nice",
        "The OS succceeded in ZIPping your life"]
    def chaos(self):
        hp = 300
        rounds = 0
        while hp > 0:
            input("Press enter to continue\n>")
            rounds += 1
            thing = self.choice(self.things)
            print(thing.replace('. ', '.\n'))
            change = re.sub(r'\[|\]', "", str(re.findall(r'[+-]\d+', thing)))
            change = change[:2] + '=' + change[2:]
            exec("hp"+re.sub("'", "", change))
            print(f"Health: {hp}")
        print("You died...")
        print(f"But survived {rounds - 1} rounds!")
randomplus=random_plus()
def __getattr__(thing):
    if hasattr(randomplus, thing): return getattr(randomplus, thing)
    else: raise AttributeError(f"Module 'randomplus' has no attribute '{thing}'")
__all__=["NonListEsqueError","NonHashError","random_plus","randomplus"]